const StatementType = {
    EXPRESSION_STATEMENT: 'EXPRESSION',
    BLOCK_STATEMENT: 'BLOCK',
    VARIABLE_DECLARATION_STATEMENT: 'VARIABLE_DECLARATION',
    IF_STATEMENT: 'IF',
    LABEL_STATEMENT: 'LABEL',
    FOR_STATEMENT: 'FOR',
    ELSE_STATEMENT: 'ELSE',
}
export default StatementType;