const BlockType = {
    KEYWORD: 'KEYWORD',
    SEPARATOR: 'SEPARATOR',
    ID: 'ID',
    ASSIGNMENT: 'ASSIGNMENT',
    LITERAL: 'LITERAL',
    VARIABLE: 'VARIABLE',
    LABEL: 'LABEL',
    LABEL_ASSIGN: 'LABEL_ASSIGN',
    OPEN_PARENTHESES: 'OPEN_PARENTHESES',
    CLOSE_PARENTHESES: 'CLOSE_PARENTHESES',
    OPERATOR: 'OPERATOR',
    FUNCTION: 'FUNCTION',
}
export default BlockType;