const BlockType = {
    VARIABLE: 'VARIABLE',
    STRING_VARIABLE: 'STRING_VARIABLE',
    NUMBER_VARIABLE: 'NUMBER_VARIABLE',
    LITERAL: 'LITERAL',
    ARITHMETIC_OPERATOR: 'ARITHMETIC_OPERATOR',
    ASSIGNMENT_OPERATOR: 'ASSIGNMENT_OPERATOR',
    COMPARISON_OPERATOR: 'COMPARISON_OPERATOR',
    LOGICAL_OPERATOR: 'LOGICAL_OPERATOR',
    BITWISE_OPERATOR: 'BITWISE_OPERATOR',
    KEYWORD: 'KEYWORD',
    SEPARATOR: 'SEPARATOR',
    LABEL: 'LABEL',
    LABEL_ASSIGN: 'LABEL_ASSIGN',
    OPEN_PARENTHESES: 'OPEN_PARENTHESES',
    CLOSE_PARENTHESES: 'CLOSE_PARENTHESES',
    FUNCTION: 'FUNCTION',
}
export default BlockType;