const LineType = {
    EXPRESSION_STATEMENT: 'EXPRESSION',
    RETURN_STATEMENT: 'RETURN',
    BLOCK_STATEMENT: 'BLOCK',
    VARIABLE_DECLARATION_STATEMENT: 'VARIABLE_DECLARATION',
    IF_STATEMENT: 'IF',
    LABEL_STATEMENT: 'LABEL',
    FOR_STATEMENT: 'FOR',
    ELSE_STATEMENT: 'ELSE',
    ELSE_IF_STATEMENT: 'ELSE_IF',
}
export default LineType;